normalize_type:
cmap: magma
output_dir: ./output
input_files:
  - path: /path/to/your/npy/file.npy
    predict_shape:
      - 1025
      - 2459
    normalize_type:
    histogram: true
  - path: ./relative/path/is/also/ok.npy
    predict_shape:
      - 1025
      - 2459
    normalize_type:
    histogram: true
